const db = supabase.createClient(ELVO_CONFIG.supabaseUrl, ELVO_CONFIG.supabasePublishableKey);
const grid=document.querySelector('#products-grid'), search=document.querySelector('#search'), sort=document.querySelector('#sort'), countEl=document.querySelector('#product-count'), pagination=document.querySelector('#pagination');
if(document.querySelector('#wa')) document.querySelector('#wa').href=ELVO_CONFIG.whatsapp;
if(document.querySelector('#ig')) document.querySelector('#ig').href=ELVO_CONFIG.instagram;
let products=[], page=1, perPage=8;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function money(n){return new Intl.NumberFormat('fa-IR').format(Number(n||0))+' تومان';}
function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-image">${p.main_image?`<img src="${p.main_image.startsWith('http')?p.main_image:`${ELVO_CONFIG.supabaseUrl}/storage/v1/object/public/product-images/${p.main_image}`}" alt="${esc(p.name)}">`:'<div class="image-placeholder">ELVO<br>WOOD</div>'}<span class="favorite">♡</span></div><div class="product-meta"><h3>${esc(p.name)}</h3><p>ابعاد: ${esc(p.dimensions||'—')}</p><strong>${money(p.price)}</strong><span class="view-product">مشاهده محصول</span></div></a></article>`}
function render(){let q=(search?.value||'').trim().toLowerCase();let list=products.filter(p=>String(p.name||'').toLowerCase().includes(q));if(sort?.value==='price-asc')list.sort((a,b)=>Number(a.price)-Number(b.price));if(sort?.value==='price-desc')list.sort((a,b)=>Number(b.price)-Number(a.price));countEl.textContent=new Intl.NumberFormat('fa-IR').format(list.length);let pages=Math.max(1,Math.ceil(list.length/perPage));page=Math.min(page,pages);let start=(page-1)*perPage;let visible=list.slice(start,start+perPage);grid.innerHTML=visible.length?visible.map(card).join(''):'<div class="empty">محصولی پیدا نشد.</div>';pagination.innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button class="${i+1===page?'active':''}" data-page="${i+1}">${new Intl.NumberFormat('fa-IR').format(i+1)}</button>`).join(''):'';pagination.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=Number(b.dataset.page);render();window.scrollTo({top:document.querySelector('#products').offsetTop-80,behavior:'smooth'})});}
async function load(){const {data,error}=await db.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error){grid.innerHTML='<div class="empty">اتصال به دیتابیس برقرار نشد.</div>';console.error(error);return}products=data||[];render()}
search?.addEventListener('input',()=>{page=1;render()});sort?.addEventListener('change',()=>{page=1;render()});load();
