const db=supabase.createClient(ELVO_CONFIG.supabaseUrl,ELVO_CONFIG.supabasePublishableKey);
const root=document.querySelector('#product-detail');
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function money(n){return new Intl.NumberFormat('fa-IR').format(Number(n||0))+' تومان';}
function imageUrl(path,bucket){if(!path)return ''; if(path.startsWith('http'))return path; return `${ELVO_CONFIG.supabaseUrl}/storage/v1/object/public/${bucket}/${path}`;}
async function load(){const id=new URLSearchParams(location.search).get('id'); if(!id){root.innerHTML='<div class="empty">محصول پیدا نشد.</div>';return;}
const {data:p,error}=await db.from('products').select('*').eq('id',id).eq('active',true).single(); if(error){root.innerHTML='<div class="empty">محصول پیدا نشد.</div>';return;}
let {data:frames}=await db.from('product_360_frames').select('*').eq('product_id',id).order('frame_index');
const gallery=(p.gallery_images||[]); const main=p.main_image; const all=[main,...gallery].filter(Boolean);
root.innerHTML=`<section class="detail-grid"><div><div class="main-photo"><img id="main-photo" src="${imageUrl(all[0],'product-images')}" alt="${esc(p.name)}"></div><div class="thumbs">${all.map((x,i)=>`<button data-src="${imageUrl(x,'product-images')}"><img src="${imageUrl(x,'product-images')}"></button>`).join('')}</div>${frames&&frames.length?`<div class="viewer"><div class="viewer-head"><h3>نمای 360 درجه</h3><span>برای چرخاندن بکشید</span></div><div class="viewer-stage"><img id="frame-img" src="${imageUrl(frames[0].frame_path,'product-360')}"></div><input id="frame-range" type="range" min="0" max="${frames.length-1}" value="0"></div>`:''}</div><div class="detail-info"><p class="eyebrow">ELVO WOOD</p><h1>${esc(p.name)}</h1><div class="price">${money(p.price)}</div><div class="specs"><div><span>ابعاد</span><b>${esc(p.dimensions||'—')}</b></div><div><span>نوع چوب</span><b>${esc(p.wood_type||'—')}</b></div><div><span>پرداخت / رنگ</span><b>${esc(p.finish_color||'—')}</b></div></div><p class="lead">${esc(p.short_description||'')}</p><div class="description">${esc(p.description||'')}</div><a class="btn contact-product" target="_blank" href="${ELVO_CONFIG.whatsapp}">استعلام و سفارش</a></div></section>`;
document.querySelectorAll('.thumbs button').forEach(b=>b.onclick=()=>document.querySelector('#main-photo').src=b.dataset.src);
if(frames&&frames.length){const range=document.querySelector('#frame-range'),img=document.querySelector('#frame-img'); const set=i=>img.src=imageUrl(frames[Number(i)].frame_path,'product-360'); range.oninput=e=>set(e.target.value); let startX=null; img.parentElement.onpointerdown=e=>startX=e.clientX; img.parentElement.onpointermove=e=>{if(startX===null)return; const dx=e.clientX-startX;if(Math.abs(dx)>8){let v=Number(range.value)-(dx>0?1:-1);v=Math.max(0,Math.min(frames.length-1,v));range.value=v;set(v);startX=e.clientX;}}; img.parentElement.onpointerup=()=>startX=null;}
}
load();